### ISSUE TITLE
Design a basic game

### ISSUE THREAD

**Issue by maxdg99** [Code4Community/platformer#6]
We want a very basic "game" with a background and a sprite.  The sprite should move on the screen with arrow keys and once they get to the end of the level, they will win. There should be a flag or something at the end.

**Comment by Tass0sm** [comment]
The last task for this issue is winning a level. Here's my rough idea for implementing that:

1. Choose a scene to work on. I think I would go with `src/scenes/hacking-scene.js`
2. Add a new function to that file called "winLevel" or something similar.
3. In that function, we want to stop the current scene and switch to a different scene. Fortunately, Phaser provides a convenient function for this exact task. You can call it with `this.phaser.switch(newScene);`

You can read more about that function [here](https://photonstorm.github.io/phaser3-docs/Phaser.Scenes.ScenePlugin.html).

I think that'll be enough to close this issue. If you're feeling excited, the next step would be to call this function under the right circumstances, which is probably on collision with a special "flag" sprite. I'll describe that process more in-depth in another issue. You can do it!
